* gm2/Make-lang.in:  modified to allow gm2 to coexist with   gcc as the linker support rather than g++.  Useful for   embedded targets which don't yet support g++.  Separated   target from host when building libraries and use separate   configure scripts for both. * gm2/README:  removed warning about development code. * gm2/config-lang.in:  added gm2lorder. * gm2/gm2.texi:  updated documentation to reflect release 1.0.   Corrected statements such as GNU Modula-2 is fully ISO   compliant. * gm2/gm2spec.c:  only include -lstdc++ if -fno-exceptions is   not present. * gm2/gm2-libs/README.texi:  tidied up dates. * gm2/gm2-libs-iso/README.texi:  corrected status of modules   given release of 1.0. * gm2/gm2-libs-iso/Strings.mod:  fixed performance bug reported   by Scott Iverson   (http://lists.nongnu.org/archive/html/gm2/2011-03/msg00035.html). * gm2/p2c/p2c.h:  test BUILD_GM2_LIBS_TARGET and include appropriate   configure header. * gm2/tools-src/makeversion:  added another consistency test. * gm2/gm2-libs/config-host.in:  new file. * gm2/gm2-libs/config-target.in:  new file. * gm2/gm2-libs/configure:  removed. * gm2/gm2-libs/configure.in:  removed.

diff --git a/tools-src/makeversion b/tools-src/makeversion
--- a/tools-src/makeversion
+++ b/tools-src/makeversion
@@ -173,10 +173,15 @@ fi
 
 #
 #  now we test the consistency of the release number in
-#  $(srcdir)/gm2/gm2-libs/configure.in
+#  $(srcdir)/gm2/gm2-libs/config-host.in
 #
 
-if [ "`grep AC_INIT ${SRCDIR}/gm2/gm2-libs/configure.in | grep ${GM2VERSION}`" == "" ] ; then
-   echo "makeversion has found a consistency error:  the ${SRCDIR}/gm2/gm2-libs/configure.in does not match the GNU Modula-2 release number"
+if [ "`grep AC_INIT ${SRCDIR}/gm2/gm2-libs/config-host.in | grep ${GM2VERSION}`" == "" ] ; then
+   echo "makeversion has found a consistency error:  the ${SRCDIR}/gm2/gm2-libs/config-host.in does not match the GNU Modula-2 release number"
+   exit 1
+fi
+
+if [ "`grep AC_INIT ${SRCDIR}/gm2/gm2-libs/config-target.in | grep ${GM2VERSION}`" == "" ] ; then
+   echo "makeversion has found a consistency error:  the ${SRCDIR}/gm2/gm2-libs/config-target.in does not match the GNU Modula-2 release number"
    exit 1
 fi
